# Copyright (c) 2026 Microchip Technology Inc.
# SPDX-License-Identifier: Apache-2.0

# Enable config log
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=8096

# Tickless kernel and PM are prerequisites for the system-timer LPM companion;
# MCHP_XEC_CCT_KTIMER then selects SYSTEM_TIMER_LPM_COMPANION_HOOKS.
CONFIG_TICKLESS_KERNEL=y

# Power management is requires to test timer LPM
CONFIG_PM=y
CONFIG_PM_DEVICE=y

# I2C-NL network layer plus DMA driver as wake capable target
CONFIG_DMA=y
CONFIG_DMA_MCHP_XEC_MAX_BLOCKS_PER_CHAN=4

CONFIG_I2C=y
CONFIG_I2C_TARGET=y
CONFIG_I2C_TARGET_BUFFER_MODE=y

# Enable driver internal state capture
CONFIG_I2C_MCHP_XEC_V3_NL_STATE_CAPTURE=y

